server:
  port: 8083
spring:
  rabbitmq:
    host: 192.168.128.129
    username: itzeng
    password: itzeng
    virtual-host: /leyou
  application:
    name: search-service
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.128.129:9300
      repositories:
        enabled: true
  jackson:
    default-property-inclusion: non_null # 配置json处理时忽略空值
  main:
    allow-bean-definition-overriding: true  # GoodsService相同的bean名
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}